#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &

bspc monitor -d I II III IV V

#bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true



# Border
bspc config focused_border_color        "#303134"
bspc config normal_border_color         "#242427"
bspc config active_border_color         "#242427"

# Autostart Scripts:

wmname bspwm &


bash ~/.config/bspwm/scripts/wallpaper &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Picom
picom &

# Network Applet
nm-applet --indicator &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# double border
~/.config/bspwm/bin/bspborder
